### Browse Books
GET http://localhost:4004/browse/Books

### Browse Books with expanded Authors
GET http://localhost:4004/browse/Books?$expand=author

### Try to insert into Books
POST http://localhost:4004/browse/Books
Content-Type: application/json

{ 
    "title": "Anna Karenina",
    "stock": 10,
    "price": 25
}
### Try to update a book
PUT http://localhost:4004/browse/Books(ID=201)
Content-Type: application/json

{
    "price": 25
}