### List all Orders - deep read
GET http://localhost:4004/admin/Orders?
&$expand=Items

### GET Orders
GET http://localhost:4004/admin/Orders

### Submit Orders - deep insert
POST http://localhost:4004/browse/Orders
Content-Type: application/json

{ 
    "book_ID":201, 
    "amount":5 
}

### Try to get the Orders
GET http://localhost:4004/browse/Orders